attempt to fix gitlab-runner pre-start

diff --git a/jobs/gitlab-runner/templates/pre-start b/jobs/gitlab-runner/templates/pre-start
--- a/jobs/gitlab-runner/templates/pre-start
+++ b/jobs/gitlab-runner/templates/pre-start
@@ -22,7 +22,9 @@ export https_proxy=<%= proxy %>
 export no_proxy=<%= proxy %>
 <% end -%>
 
-runuser -u vcap -- /var/vcap/packages/gitlab-runner/bin/gitlab-runner register \
+for i in 1 2 3
+do
+if ! runuser -u vcap -- /var/vcap/packages/gitlab-runner/bin/gitlab-runner register \
   --non-interactive \
   --config "${STORE_DIR}/config.toml" \
   --name "${RUNNER_NAME}" \
@@ -54,6 +56,9 @@ runuser -u vcap -- /var/vcap/packages/gitlab-runner/bin/gitlab-runner register \
   --env no_proxy="<%= p('env.no_proxy', '') %>" \
   --env FF_GITLAB_REGISTRY_HELPER_IMAGE="<%= p('env.FF_GITLAB_REGISTRY_HELPER_IMAGE', '1') %>" \
   --token <%= p('runner.registration.token') %>
+then echo "error: during the registration process ($i)"
+fi
+done
 
 sed -i \
 	-e '/log_format/d' \
